version: 0.9.{branch}.{build}.

clone_depth: 10
shallow_clone: true
cache: '%LOCALAPPDATA%\\Yarn'
build:
  verbosity: minimal

environment:
  nodejs_version: "9"

install:
  # yarn issue with cross-env
  - ps: Install-Product node $env:nodejs_version
  - npm install --global cross-env
  - yarn install

build_script:
  - yarn run lint
  - yarn run build
  - yarn run dist

test_script:
  - cmd: yarn run test:ci-on-windows

deploy: off
